version: "3.9"

services:
  backend:
    image: multi-company-sales-system
    container_name: multi-company-sales-system
    ports:
      - "9090:9090"
    environment:
      APP_NAME: "Multi-Company Sales System"
      APP_VERIFICATION_CODE_LENGTH: "6"
      APP_VERIFICATION_CODE_TTL_MINUTES: "15"
      APP_VERIFICATION_MAX_ATTEMPTS: "5"

      DB_URL: "jdbc:postgresql://postgres:5432/Sales"
      DB_USERNAME: "postgres"
      DB_PASSWORD: "12345678"

      SMTP_HOST: "smtp.gmail.com"
      SMTP_PORT: "587"
      SMTP_USER: "qpan609@gmail.com"
      SMTP_PASS: "jpqhssapqiusqenz"
      SMTP_AUTH: "true"
      SMTP_STARTTLS: "true"

      APP_ADMIN_KEY: "SuperClaveUltraSegura123"

      JWT_SECRET: "qP6B82/hRz2KeC0I5VgN0SglSk0wQezpA2S+KnjdQfE="
      JWT_EXP_MINUTES: "60"

    depends_on:
      - postgres

  postgres:
    image: postgres:16
    container_name: mc_postgres
    environment:
      POSTGRES_DB: Sales
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
    ports:
      - "5432:5432"
